# SITE CONFIGURATION
title: Ben's Tech Blog # your site title
author: GitHub User # You :P
description: > # Meta description of Homepage
  About Data Science
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hjben.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: hjben
  links:
    - https://twitter.com/BenBalter
    - https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/BenBalter
    - https://plus.google.com/+BenBalter
    - https://github.com/benbalter
    - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Category', link: '/category'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Welcome to visit my blog

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: hj.ben.kim@gmail.com # email for form submission

# twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username:  hjben # replace with your_github_username or comment to remove link from footer
# instagram_username: ben_likes_ # replace with your_instagram_username or comment to remove link from footer
linkedin_username: hyunjoong-kim-72b523143

disqus:
  shortname: hjben # to enable comments replace with your_disqus_shortname

tipue_search:
  include:
    pages: false
      collections: []
  exclude:
    files: [search.html, index.html, tags.html]
      categories: []
      tags: []

google_tag_manager: GTM-TXCBNFJ # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
